version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: "./config.json"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_dev}"
      POSTGRES_USER: "${POSTGRES_USER_dev}"
      POSTGRES_DB: "${POSTGRES_DB_dev}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
